### ISSUE TITLE
Show target path on camera window

### ISSUE THREAD

**Issue by beini19** [uwnrg/minotaur-cpp#133]
- Add a UI element to draw intended path for robot motion over the camera display
- Store target path globally

**Comment by wyxzou** [comment]
The idea is to drag over the buttons used fro the wall drawing gui to select a path?

**Comment by beini19** [comment]
Yup, this feature specifically should just display the target path calculated by the A* algorithm on the video feed. There's no interaction with the wall-drawing GUI required.

**Comment by Mogball** [comment]
@wyxzou Imma snatch this
