### ISSUE TITLE
Add about dialog

### ISSUE THREAD

**Issue by sadmansk** [uwnrg/minotaur-cpp#19]

**Comment by sadmansk** [comment]
### minotaur
#### v0.01
minotaur is a software developed by the University of Waterloo NanoRobotics Group for controlling micro-robots. The source code is GPL licensed and available at [UWNRG Github](https://github.com/uwnrg).

[button here] -> list of contributors:
- Sadman Kazi
- Tammy Liu
- Jeff Niu
- William Zou
- Ahmed Sabie

**Comment by aneedalie** [comment]
Closed by https://github.com/uwnrg/minotaur-cpp/pull/24
