### ISSUE TITLE
Remove log window and save logs to file

### ISSUE THREAD

**Issue by Mogball** [uwnrg/minotaur-cpp#196]
We might as well just log to console, and have minotaur save a log file each instance so we can view it after running.

**Comment by bretsky** [comment]
Instead of removing the log window, we can just start by logging to a file and keeping the log window.

**Comment by bretsky** [comment]
![log](https://user-images.githubusercontent.com/11529474/48167071-8c451e80-e2b8-11e8-817f-f72a904e73ac.png)
Anything that gets output here should also be saved to a file. (Don't modify the individual parts of the code where logging gets called, modify the class that does the logging [`logger.cpp`] to ensure that all data is logged)
