### ISSUE TITLE
Add instructions for setting up the camera

### ISSUE THREAD

**Issue by sadmansk** [uwnrg/minotaur-cpp#20]
Follow the instructions here: https://github.com/TheImagingSource/tiscamera/wiki/Getting-Started-with-USB-2.0-cameras-on-a-Raspberry-PI-or-on-other-Linux-Systems and here: https://github.com/TheImagingSource/tiscamera/wiki/First-Steps

**Comment by sadmansk** [comment]
@jingyli would you be able to work on this actually? I'm not able to verify the steps, so it's better if you follow these instructions when you go to the lab the next time, and document the steps as you go in the wiki.

**Comment by jingyli** [comment]
@sadmansk Yep, I can do that. I'll let you know when I find a time to go into the lab.

**Comment by aneedalie** [comment]
Closed for the same reason as: https://github.com/uwnrg/minotaur-cpp/pull/40
