### ISSUE TITLE
Make "About" dialog prettier

### ISSUE THREAD

**Issue by aneedalie** [uwnrg/minotaur-cpp#32]

**Comment by wyxzou** [comment]
Can you assign me to this issue?

**Comment by aneedalie** [comment]
Go ahead and assign it to yourself! :)

**Comment by wyxzou** [comment]
![image](https://user-images.githubusercontent.com/15041340/31592414-0ccb6dd8-b1f6-11e7-91cd-8149b85322e2.png)

**Comment by sadmansk** [comment]
Closed by #41
