### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by uwnrg-controls** [uwnrg/minotaur-cpp#53]
I can no longer run the code using the same instructions as the README on the controls laptop.

**Comment by Mogball** [comment]
@uwnrg-controls Please see the instructions at the bottom of `CONTRIBUTING.md` and see if they do anything (i.e. try running `vagrant_setup.sh`).

**Comment by uwnrg-controls** [comment]
On that note, for organization I'd like to see the `README.md` have just things pertaining to running the code on the controls laptop, and everything else in `CONTRIBUTING.md`

**Comment by Mogball** [comment]
Kinda weird not knowing who I'm talking to lol.

Currently there are no documents specifically for the controls laptop. @sadmansk wanted general setup information in `README.md` (i.e. for Windows, MacOS, etc.) and virtual environment (i.e. Vagrant but should apply to most Ubuntu versions) are in `CONTRIBUTING.md`

**Comment by uwnrg-controls** [comment]
I thought we can only run the code using `cmake` now, so some of the build info in the `README` is also outdated? Correct me if I'm wrong.

If that's the case when we should reconsider how we want to structure the documents.

**Comment by Mogball** [comment]
`README.md` is outdated. And you do need to use `cmake`

The PR to update it is still open @sadmansk.

**Comment by uwnrg-controls** [comment]
I managed to get past the `cmake ../` part, but now I'm getting these errors:
```
make: *** No rule to make target 'code/gui/pythoninterpreter.ui', needed by 'ui_pythoninterpreter.h'.  Stop.

**Comment by Mogball** [comment]
@uwnrg-controls sounds like there might be an issue with how Qt is set up, or you may have needed to do a clean, anyway ping me on slack next time

**Comment by sadmansk** [comment]
@aneedalie verify if #49 fixed the issue.

**Comment by aneedalie** [comment]
Will verify when I get into the lab by the end of exams.

**Comment by sadmansk** [comment]
@aneedalie were you able to verify? I haven't tried building in a while so wanted to make sure if the instructions are now up to date.

**Comment by aneedalie** [comment]
Verified that it works properly! This can be closed.
