### ISSUE TITLE
Demo Video Preparation

### ISSUE THREAD

**Issue by beini19** [uwnrg/minotaur-cpp#70]
### Code maintenance
- [x] Clean up old actuator code

### Features necessary for Demo Video
- [x] Add video recording feature 
  * Functionality: button that opens a `Save File` window
  * Starts recording after file is selected and then stops when pressed again
  * [QFileDialog](http://doc.qt.io/qt-5/qfiledialog.html)
  * Add to `camera.h`
- [x] Add label to take pic

### Features necessary for autonomous motion
- [x] Add object tracking capability
- [ ] Basic A* implementation, with room to modify
- [ ] Implement basic navigation algorithn

From February 1 meeting

**Comment by beini19** [comment]
@sadmansk @aneedalie

**Comment by Mogball** [comment]
@sadmansk @aneedalie
