### ISSUE TITLE
Arduino port autodetection

### ISSUE THREAD

**Issue by Manoflast3** [uwnrg/minotaur-cpp#75]
Currently Minotaur is hardcoded to use ttyacm0. This causes annoying issues when the board is not using ttyacm0. 

It's not consistent to always expect the Arduino to use ttyacm0 as the camera will sometimes occupy ttyacm0 after the laptop goes to sleep and wakes up.

**Comment by Mogball** [comment]
[QSerialPortInfo](http://doc.qt.io/qt-5/qserialportinfo.html)
