### ISSUE TITLE
Simulator needs to be updated to match physics of actual robot.

### ISSUE THREAD

**Issue by Manoflast3** [uwnrg/minotaur-cpp#76]
Currently, movement is too smooth. Tweaks need to be made so the acceleration matches how it behaves in competition. I'm also having @laurazhukas look into this as well.  

It'd be useful to have a simulation environment so you could actually train the robot's movements (if we plan to go this route).

**Comment by Mogball** [comment]
I agree, I made this without any actual knowledge of the setup a long time ago xd

**Comment by uwnrg-controls** [comment]
#88
