### ISSUE TITLE
Input Buffer for Solenoid Class

### ISSUE THREAD

**Issue by uwnrg-controls** [uwnrg/minotaur-cpp#86]
The solenoid controller needs to queue inputs into a buffer and process them in another thread

**Comment by wyxzou** [comment]
@Mogball I would prefer put the queue in the Controller class rather than the Solenoid class. It would be nice if we queued the instructions through m_controller in the mainwindow.cpp. The code is nicer and calling it through m_solenoid breaks something in moc_solenoid. Any suggestions?

**Comment by wyxzou** [comment]
(Plus in the far off future, when we program for MAYA or SAW, we'd probably have to use a queue for their controllers as well)

**Comment by Mogball** [comment]
@wyxzou The controller class is also used for the simulator. We don't want to be queuing inputs for something that runs inside minotaur. If you're thinking about future uses you could make another subclass of controller to extend with solenoid
